### ISSUE TITLE
Custom UIWindow

### ISSUE THREAD

**Issue by harmjanr** [fmo91/PluggableApplicationDelegate#8]
For my project, I need to have a custom UIWindow. Without the PluggableApplicationDelegate, I used to do it like this:
```
    var customWindow: MyCustomWindow?
    var window: UIWindow? {
        get {
            customWindow = customWindow ?? MyCustomWindow(frame: UIScreen.main.bounds)
            return customWindow
        }
    }
```

When I keep this code in my AppDelegate itself, I get the following error on the var Window: 
> Overriding non-open var outside of its defining module

And when I put this code in a specific ApplicationService, it says that self.window is unknown. 

Any clue how I can still have this custom UIWindow? Thanks!

**Comment by jortberends** [comment]
To be able to override the window, the window var in PluggableApplicationDelegate should be open, not public.

**Comment by stami** [comment]
Hi!

The creator doesn't seem to be very active here so I'll answer what I did.

You can access to `window` by overriding AppDelegate initializer like this:

```
import UIKit
import PluggableApplicationDelegate

@UIApplicationMain
class AppDelegate: PluggableApplicationDelegate {

  override init() {
    super.init()
    self.window = UIWindow(frame: UIScreen.main.bounds)
  }

  override var services: [ApplicationService] {
    return [
      CustomAppearanceService()
    ]
  }
}

```

**Comment by harmjanr** [comment]
@stami This works great, didn't think of this way. Thanks!
